
variable "chain_name" {
  description = ""
  type        = string
}

variable "keys_octoup" {
  description = "Keys generated by octokey. https://github.com/octopus-network/octokey"
  type        = list(map(string))
}

variable "module_depends_on" {
  description = "Any to have module depend on"
  type        = any
  default     = []
}

variable "namespace" {
  description = "Namespace"
  type        = string
  default     = "default" # devnet / testnet / mainnet
}

variable "deploy_version" {
  description = "Deployment version"
  type        = string
}